# Generated by Django 5.2.8 on 2025-11-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaestado',
            name='color',
            field=models.CharField(choices=[('rojo', 'Rojo'), ('verde', 'Verde'), ('amarillo', 'Amarillo')], default='verde', max_length=10),
        ),
    ]
