# Generated by Django 5.2.8 on 2025-11-13 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_mesaestado_color'),
    ]

    operations = [
    ]
